In [2]:
import sys
import os
# Add the 'scripts/' directory to the system path
sys.path.append(os.path.abspath('../triple_mbhb'))

In [3]:
import numpy as np
import random
import pandas as pd
from tables_merger_fraction import *
import BH_kicks as kicks
import merger_rate_calculate as mr

In [4]:
import h5py

In [9]:
file_path='/Users/pranavsatheesh/Triples/Github/Triple-Outcomes/Data/'

In [10]:
strong_triples_file_path = file_path + "strong_triples_data_from_ill.h5"

In [12]:
with h5py.File(strong_triples_file_path, 'r') as hf:
    for key in hf.keys():
       hf[key][:]  

In [13]:
hf = h5py.File(strong_triples_file_path, 'r')

In [18]:
hf['bhid_inner'][:][0]

array([9223372036337899864, 9223372036518620732], dtype=uint64)

In [19]:
hf['bhid_outer'][:][0]

array([9223372036417148615, 9223372036518620732], dtype=uint64)

In [22]:
hf['sep'][:][0]

array([4.78219325e+02, 4.30397392e+02, 3.87357653e+02, 3.48621888e+02,
       3.13759699e+02, 2.82383729e+02, 2.54145356e+02, 2.28730820e+02,
       2.05857738e+02, 1.85271965e+02, 1.66744768e+02, 1.50070291e+02,
       1.35063262e+02, 1.21556936e+02, 1.09401242e+02, 9.84611181e+01,
       8.86150063e+01, 7.97535057e+01, 7.17781551e+01, 6.46003396e+01,
       5.81403056e+01, 5.23262751e+01, 4.70936476e+01, 4.23842828e+01,
       3.81458545e+01, 3.43312691e+01, 3.08981422e+01, 2.78083280e+01,
       2.50274952e+01, 2.25247456e+01, 2.02722711e+01, 1.82450440e+01,
       1.64205396e+01, 1.47784856e+01, 1.33006371e+01, 1.19705733e+01,
       1.07735160e+01, 9.69616441e+00, 8.72654797e+00, 7.85389317e+00,
       7.06850386e+00, 6.36165347e+00, 5.72548812e+00, 5.15293931e+00,
       4.63764538e+00, 4.17388084e+00, 3.75649276e+00, 3.38084348e+00,
       3.04275913e+00, 2.73848322e+00, 2.46463490e+00, 2.21817141e+00,
       1.99635427e+00, 1.79671884e+00, 1.61704696e+00, 1.45534226e+00,
      

In [16]:
hf['M1'][:]

array([1.59597705e+07, 2.64796348e+08, 2.25508947e+08, 9.44437283e+07,
       2.95006187e+07, 3.48995006e+07, 2.38511641e+08, 1.10763159e+07,
       4.20108627e+07, 1.42724513e+07, 3.95813067e+07, 3.73208349e+07,
       7.46320470e+07, 1.83242694e+07, 6.54750996e+06, 6.44206044e+08,
       4.46052560e+06, 3.72679022e+07, 1.45750762e+07, 2.68159835e+08,
       3.57963389e+07, 8.61248638e+08, 3.26071138e+07, 3.94000426e+07,
       7.99591029e+06, 1.84726165e+08, 2.45636383e+07, 1.59149767e+07,
       1.79413483e+08, 5.12376853e+07, 5.31387563e+08, 2.49903980e+07,
       5.15749440e+07, 2.88702945e+07, 3.54799052e+07, 2.56553775e+08,
       1.57243603e+08, 1.49655137e+07, 2.53903626e+06, 3.12650019e+08,
       6.74546431e+07, 2.44149852e+07, 8.60474896e+07, 3.48660926e+06,
       6.18053684e+08, 9.33736151e+06, 2.47063392e+07, 8.52408490e+06,
       2.11113435e+07, 3.50203379e+07, 3.05670267e+08, 2.77733298e+06,
       1.98391034e+07, 6.10109098e+06, 3.55034390e+08, 1.07055985e+07,
      

In [23]:
import find_triple_mbhs as ftm
import read_mbhb
import numpy as np
import pandas as pd
from tqdm import tqdm
np.seterr(divide='ignore', invalid='ignore')
import h5py

In [24]:
import triple_n_binary_file_maker as mstest
import stalled_triple_model as stall

merger_file_path = '/Users/pranavsatheesh/Triples/Github/Illustris_Data/mbhb_data/' #path to the merger file 
fmrg='ill-1_blackhole_mergers_fixed.npz'  #merger file

In [25]:
mst = mstest.ms_tests(path = merger_file_path, fmbhb='new_fid_e06' , mergers = np.load(merger_file_path+fmrg), calculate_tinsp=True, parse_env=True) 

h = 0.6774, tH = 13802718326.81273 yr.

Reading data from /Users/pranavsatheesh/Triples/Github/Illustris_Data/mbhb_data/new_fiducial_mbhb-evolution_with_env_in_ecc-evo-0.6_lc-shm06.hdf5
subhalo SFR:
0.0 702.5588989257812 0.8404439966052046
snapshot:  (9234,) 43 135 9234
dadt.size:  2049948 (9234, 222)
masses:  (9234, 2)
times:  (9234, 222)
scales:  (9234, 222)

File contains 9234 binaries.
Nmbhb in nested class:  9234


Calculating inspiral time for all binaries all separations: 100%|██████████| 9234/9234 [00:11<00:00, 783.85it/s]


min/max/size sim_tmrg_1st:  -1.0 13583238290.476427 9234
min/max/size evol_tmrg_1st:  -1.0 3.1010641661682496e+16 9234
min/max/size sim_tmrg_2nd:  -1.0 13739111457.429827 9234
min/max/size evol_tmrg_2nd:  -1.0 4.300186751091767e+16 9234


In [29]:
np.shape(mst.inner_binary_seps)

(2029, 222)

In [30]:
strong_in_triple_mask = mst.q_inner_outer_strong()

In [38]:
mst.sep[mst.triple_mask]

array([[ 478.2193246 ,  430.39739214,  387.35765293, ...,    0.        ,
           0.        ,    0.        ],
       [1011.45179667,  910.306617  ,  819.2759553 , ...,    0.        ,
           0.        ,    0.        ],
       [ 786.79916282,  708.11924654,  643.37370096, ...,    0.        ,
           0.        ,    0.        ],
       ...,
       [2885.19946613, 2596.67951952, 2337.01156756, ...,    0.        ,
           0.        ,    0.        ],
       [4661.36869902, 4484.92280383, 4369.69188278, ...,    0.        ,
           0.        ,    0.        ],
       [2952.70867639, 2657.43780875, 2391.69402788, ...,    0.        ,
           0.        ,    0.        ]])

In [42]:
mst.sep[mst.strong_triple_mask]

array([[ 478.2193246 ,  430.39739214,  387.35765293, ...,    0.        ,
           0.        ,    0.        ],
       [ 786.79916282,  708.11924654,  643.37370096, ...,    0.        ,
           0.        ,    0.        ],
       [ 876.15260446,  788.53734401,  709.68360961, ...,    0.        ,
           0.        ,    0.        ],
       ...,
       [2819.79516972, 2537.81565275, 2284.03408748, ...,    0.        ,
           0.        ,    0.        ],
       [1738.93863172, 1565.04476855, 1408.5402917 , ...,    0.        ,
           0.        ,    0.        ],
       [2047.30207982, 1842.57187184, 1658.31468466, ...,    0.        ,
           0.        ,    0.        ]])

In [43]:
mst.dadt[mst.strong_triple_mask]

array([[-1.64362964e-03, -2.29166894e-03, -1.95272800e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.38768742e-05, -2.28069221e-05, -1.05620641e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.74175409e-05, -2.42618642e-05, -2.14708819e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-9.75631458e-05, -9.61792275e-05, -9.84486484e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.85176454e-05, -5.71507532e-05, -5.75452191e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.47125855e-04, -1.32540934e-04, -1.03923299e-04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [46]:
mst.inner_binary_dadt[strong_in_triple_mask]

array([[-1.64362964e-03, -2.29166894e-03, -1.95272800e-03, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-6.38768742e-05, -2.28069221e-05, -1.05620641e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.74175409e-05, -2.42618642e-05, -2.14708819e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-9.75631458e-05, -9.61792275e-05, -9.84486484e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-5.85176454e-05, -5.71507532e-05, -5.75452191e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-1.47125855e-04, -1.32540934e-04, -1.03923299e-04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [44]:
mst.outer_binary_dadt[strong_in_triple_mask]

array([[-1.26997767e-02, -1.39032783e-02, -1.19147310e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.14639283e-05, -1.67137329e-05, -1.31129218e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.69320305e-05, -1.87284054e-05, -1.29873616e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       ...,
       [-5.27500280e-05, -4.53840858e-05, -3.83034768e-05, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.61932311e-04, -3.77009266e-04, -3.83582974e-04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-3.61932311e-04, -3.77009266e-04, -3.83582974e-04, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [41]:
mst.outer_binary_seps[strong_in_triple_mask]

array([[1277.42048169, 1149.67843352, 1034.71059017, ...,    0.        ,
           0.        ,    0.        ],
       [2568.01966548, 2504.32091341, 2454.71937207, ...,    0.        ,
           0.        ,    0.        ],
       [2906.05797615, 2736.90231496, 2619.27227587, ...,    0.        ,
           0.        ,    0.        ],
       ...,
       [2491.05613476, 2241.95052129, 2017.75546916, ...,    0.        ,
           0.        ,    0.        ],
       [3352.79570471, 3017.51613424, 2715.76452081, ...,    0.        ,
           0.        ,    0.        ],
       [3352.79570471, 3017.51613424, 2715.76452081, ...,    0.        ,
           0.        ,    0.        ]])

In [39]:
mst.inner_binary_seps[strong_in_triple_mask]

array([[ 478.2193246 ,  430.39739214,  387.35765293, ...,    0.        ,
           0.        ,    0.        ],
       [ 786.79916282,  708.11924654,  643.37370096, ...,    0.        ,
           0.        ,    0.        ],
       [ 876.15260446,  788.53734401,  709.68360961, ...,    0.        ,
           0.        ,    0.        ],
       ...,
       [2819.79516972, 2537.81565275, 2284.03408748, ...,    0.        ,
           0.        ,    0.        ],
       [1738.93863172, 1565.04476855, 1408.5402917 , ...,    0.        ,
           0.        ,    0.        ],
       [2047.30207982, 1842.57187184, 1658.31468466, ...,    0.        ,
           0.        ,    0.        ]])